#!/usr/bin/env python3
"""
Appending functions for report building

Implements the appending pattern similar to report_generator.py for 
progressive content building with memory efficiency and progress saving.
"""

from datetime import datetime
from pathlib import Path
from signalmuse.utils.utils import config, generate_timestamp_filename


def create_report() -> str:
    """
    Create initial report file with header
    
    Returns:
        str: Path to the created report file
    """
    filename = generate_timestamp_filename("market_report", "md")
    report_path = config.output_dir / filename
    
    # Initialize report with header
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(f"# Market Report - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        f.write("Generated by SignalMuse Article Generator Module\n\n")
        f.write("---\n\n")
    
    return str(report_path)


def append_to_report(report_path: str, content: str, section_type: str):
    """
    Append content to report with proper formatting
    
    Args:
        report_path: Path to the report file
        content: Content to append  
        section_type: Type of section ('earnings' or 'impact')
    """
    with open(report_path, 'a', encoding='utf-8') as f:
        # Add section headers
        if section_type == 'earnings':
            f.write("## Earnings Section\n\n")
        elif section_type == 'impact':
            f.write("## Market Impact Section\n\n")
        
        # Append content with proper spacing
        f.write(content + "\n\n")
        f.write("---\n\n")  # Section separator
